### PR TITLE
Parse ACL files properly

### PR DESCRIPTION
**Pull request by Mygod**
Look at that massive regexp. Beautiful. :haircut_woman:

### CODE REVIEW

**Comment by madeye** [comment]
Is this abusing regexp? 😓

**Comment by Mygod** [comment]
Uhhhh no? Why? [Go's regexp is guaranteed to run in linear time anyways](https://golang.org/pkg/regexp/). We'd better make full use of that.

**Comment by madeye** [comment]
Okay, good to know...

**Comment by Mygod** [comment]
Here's [a little trivia](https://stackoverflow.com/questions/2245282/what-is-the-longest-regular-expression-you-have-seen). Honestly I'd think this might run even faster than an actual Subnet parser (minus initial compilation time) if the underlying matching procedure is just a DFA.

**Comment by madeye** [comment]
I'm debugging a matching issue for days. And it turns out related to this patch.

With this patch, an empty line would also be compiled to a regexp, which matches everything...

**Comment by Mygod** [comment]
Huh lol that makes sense. Maybe ignore empty lines?

**Pull request merged**
